version: '3'

services:
  srpapp:
    container_name: srp_app
    build: srp_app/.
    ports:
      - 5000:5000
    networks:
      - project

  srp_app:
    container_name: fail_srp_app
    build: srp_app_/.
    ports:
      - 5000:4000
    networks:
      - project

  srp_app_nodejs:
    container_name: srp_app_nodejs
    build: srp_app_nodejs/.
    ports:
      - 8080:8080
    networks:
      - project

  srp_app_python:
    container_name: srp_app_python
    build: srp_app_nodejs/.
    ports:
      - 8080:7070
    networks:
      - project
      
networks:
  project: